// The Russian interface: the same keys as `en` in src/strings.ts (a test fails if they differ), written the way a Russian app would say
// it rather than word for word. The mode names Learn, Review, Matching, Cloze and Words stay in Latin: they are the names of the app's
// own screens. Plurals go through `plural` (один / несколько / много). Debug stays English (strings.shared.ts).
import { plural } from './lib/plural'
import type { Strings } from './strings'
import { card, debug, wordContent } from './strings.shared'

/** слово / слова / слов */
const words = (n: number) => plural(n, { one: 'слово', few: 'слова', many: 'слов' })

export const ru: Strings = {
  appTitle: 'Riopalabras',

  common: {
    back: 'Назад',
    retry: 'Повторить',
    backToHome: 'На главный экран',
    loading: 'Загружаем ваши слова…',
    reload: 'Обновить',
    signInPrompt: 'Откройте приложение в Telegram, чтобы войти.',
    loadFailed: (message) => `Не удалось загрузить данные: ${message}`,
  },

  home: {
    toReviewToday: 'Повторить сегодня',
    newToLearn: 'Новые слова',
    learn: 'Learn',
    learnWithCount: (n) => `Учить новые слова (${n})`,
    learnCapReached: 'Дневной лимит исчерпан',
    learnPoolEmpty: 'Новых слов пока нет',
    reviewWithCount: (n) => `Повторить слова (${n})`,
    reviewNothingDue: 'Повторять нечего',
    degradedTables: { user_favorites: 'избранное', user_hidden_words: 'скрытые слова' },
    degraded: (tables) => `Пока не удалось загрузить: ${tables.join(' и ')}. Пробуем снова в фоне.`,
    degradedHiddenWarning: 'Пока всё не загрузится, скрытые вами слова могут показываться.',
    retryNow: 'Повторить сейчас',
    streak: (n) => `${n} ${plural(n, { one: 'день', few: 'дня', many: 'дней' })} подряд`,
    weekdays: ['П', 'В', 'С', 'Ч', 'П', 'С', 'В'],
    streakDots: (active) => `Активность: ${active} из последних 7 дней`,
    wotdPill: 'palabra del día',
    wotdTitle: 'Слово дня',
    seeCard: 'Открыть карточку →',
    tiles: {
      learn: { label: 'Learn', es: 'aprender' },
      review: { label: 'Review', es: 'repasar' },
      matching: { label: 'Matching', es: 'parejas' },
      cloze: { label: 'Cloze', es: 'completar' },
    },
    wordsButton: 'Words',
    settingsButton: 'Настройки',
    unsavedProgress: 'Часть прогресса ещё не сохранена. Пробуем снова…',
    signInRejected: 'Прогресс не сохраняется: вход отклонён. Нажмите «Повторить сейчас» или закройте приложение и откройте его снова, чтобы войти заново.',
  },

  words: {
    title: 'Words',
    detailTitle: 'Слово',
    searchPlaceholder: 'Поиск: испанский, английский или русский',
    searchLabel: 'Поиск по словам',
    segments: { all: 'Все', learned: 'Выученные', hidden: 'Скрытые' },
    segmentsLabel: 'Какие слова показывать',
    filtersButton: 'Фильтры',
    sortButton: (current) => `Сортировка: ${current}`,
    filtersActive: (n) => `Включено фильтров: ${n}`,
    sheet: {
      close: 'Закрыть',
      filtersTitle: 'Фильтры',
      clearAll: 'Сбросить всё',
      sortTitle: 'Сортировка',
      progress: 'Прогресс',
      showOnly: 'Показывать только',
      partOfSpeech: 'Часть речи',
      anyProgress: 'Любой',
    },
    states: { new: 'Не начато', learning: 'В процессе', established: 'Знаю хорошо', due: 'Пора повторить' },
    favourites: 'Избранное',
    queued: 'В очереди',
    pos: { verb: 'Глаголы', noun: 'Существительные', adj: 'Прилагательные', adv: 'Наречия' },
    sorts: { frequency: 'По частоте', az: 'По алфавиту', due: 'Ближайшие повторы', recent: 'Недавно выученные', random: 'В случайном порядке' },
    bestMatch: 'Лучшее совпадение',
    posTag: { n: 'сущ.', v: 'гл.', adj: 'прил.', adv: 'нар.', pron: 'мест.', num: 'числ.', prep: 'предл.', determiner: 'опр.', conj: 'союз', interj: 'межд.', letter: 'буква', contraction: 'слитн.', art: 'артикль' },
    due: 'Пора повторить',
    stateName: { hidden: 'Скрыто', reference: 'Только для справки', due: 'Пора повторить', established: 'Знаю хорошо', learning: 'В процессе', new: 'Не начато' },
    favourite: (word) => `Добавить «${word}» в избранное`,
    unfavourite: (word) => `Убрать «${word}» из избранного`,
    addFavourite: 'В избранное',
    removeFavourite: 'Убрать из избранного',
    queueForLearn: 'В очередь Learn',
    removeFromQueue: 'В очереди — убрать',
    queuedAt: (place) => `Поставлено в очередь: ${place}-е место.`,
    queueFull: (max) => `Очередь заполнена (${max} ${words(max)}). Уберите одно слово, чтобы добавить другое.`,
    beyondToday: 'Не войдёт в сегодняшнюю порцию',
    custom: 'Мои слова',
    addWord: 'Добавить слово',
    customMark: 'Добавлено вами',
    editWord: 'Изменить',
    deleteWord: 'Удалить',
    added: 'Слово добавлено и поставлено в очередь Learn.',
    addedNotQueued: (max) => `Слово добавлено. Очередь Learn заполнена (${max} ${words(max)}), поэтому в очередь оно не попало.`,
    saved: 'Сохранено.',
    deleteTitle: (word) => `Удалить «${word}»?`,
    deleteBody: 'Слово исчезнет из вашего списка. Если добавить его снова, вернётся и прогресс, который вы по нему накопили.',
    deleteConfirm: 'Удалить',
    deleteCancel: 'Отмена',
    form: {
      addTitle: 'Новое слово',
      editTitle: 'Изменить слово',
      spanish: 'Слово по-испански',
      spanishHint: 'Одно слово, не длиннее 50 символов.',
      pos: 'Часть речи',
      posNames: { v: 'Глагол', n: 'Существительное', adj: 'Прилагательное', adv: 'Наречие', custom: 'Другое' },
      continue: 'Дальше',
      change: 'Изменить',
      problems: {
        empty: 'Введите слово по-испански.',
        spaces: 'Только одно слово: фразы пока не поддерживаются.',
        'too-long': 'Слишком длинное: больше 50 символов.',
        pos: 'Выберите часть речи.',
        translations: 'Нужны оба перевода: слово только с одним переводом нельзя ни учить, ни повторять.',
      },
      duplicate: (typed, existing, via) =>
        via === 'es_word' ? `Слово «${existing}» уже есть в вашем списке.` : `Слово «${typed}» уже есть в вашем списке: это риоплатская форма слова «${existing}».`,
      openExisting: (word) => `Открыть «${word}»`,
      looking: 'Ищем перевод…',
      fillMyself: 'Заполню сам',
      ru: 'Перевод на русский',
      en: 'Перевод на английский',
      translationsHint: 'Нужны оба перевода: слово только с одним переводом нельзя ни учить, ни повторять.',
      example: 'Пример предложения (необязательно)',
      exampleEn: 'Пример на английском (необязательно)',
      exampleRu: 'Пример на русском (необязательно)',
      rioplatenseForm: (form) => `Риоплатская форма: ${form}`,
      rioplatenseCheck: 'Это риоплатское слово',
      rioplatenseHint: 'Регион, стиль речи и стандартное слово ниже показываются на карточке, только если это включено.',
      region: 'Регион',
      regionHint: 'Где употребляется риоплатское слово. Оставьте «Неизвестно», если оно в ходу в обеих странах или вы не уверены.',
      regionNames: { ar: 'Только Аргентина', uy: 'Только Уругвай' },
      register: 'Стиль речи',
      registerNames: { neutral: 'Нейтральное', informal: 'Разговорное', vulgar: 'Вульгарное', offensive: 'Оскорбительное', pejorative: 'Пренебрежительное' },
      unknown: 'Неизвестно',
      standard: 'Эквивалент в стандартном испанском',
      standardHint: 'Для риоплатского слова: обычное слово, например «calabacín» для «zapallito». Необязательно.',
      filled: 'Заполнено автоматически. Перед сохранением всё можно изменить.',
      spelling: {
        didYouMean: (suggestion) => `Вы имели в виду ${suggestion}?`,
        notRecognised: (word) => `Слово «${word}» не распознано как испанское.`,
        notRecognisedSave: (word) => `Слово «${word}» не распознано как испанское. Его всё равно можно сохранить.`,
        use: (suggestion) => `Исправить на ${suggestion}`,
        keep: (word) => `Оставить ${word}`,
      },
      save: 'Сохранить',
      cancel: 'Отмена',
      discardTitle: 'Закрыть без сохранения?',
      discardBody: 'Всё, что вы заполнили, пропадёт.',
      discard: 'Закрыть',
      keepEditing: 'Продолжить',
    },
    enrich: {
      offline: 'Нет соединения, поэтому перевод подставить не удалось. Введите его сами.',
      unauthorized: 'Вход не принят, поэтому перевод подставить не удалось. Введите его сами или закройте приложение и откройте снова.',
      dailyQuota: (usage, limit) =>
        `Сегодня использовано ${usage} из ${limit} ${plural(limit, { one: 'автоматического перевода', few: 'автоматических переводов', many: 'автоматических переводов' })}. Введите перевод сами или попробуйте завтра.`,
      rateLimit: 'Слишком много запросов. Попробуйте через минуту или введите перевод сами.',
      busy: 'Сервис переводов сейчас перегружен. Попробуйте позже или введите перевод сами.',
      timeout: 'Сервис переводов не ответил вовремя. Введите перевод сами или попробуйте ещё раз.',
      network: 'Не удалось связаться с сервисом переводов. Введите перевод сами или попробуйте ещё раз.',
      noResult: 'Сервис не нашёл перевода для этого слова. Введите его сами.',
      other: (status) => (status ? `Сервис переводов вернул ошибку (${status}). Введите перевод сами или попробуйте ещё раз.` : 'Сервис переводов недоступен. Введите перевод сами.'),
    },
    bringBack: 'Вернуть',
    bringBackWord: (word) => `Вернуть «${word}»`,
    emptyLearned: 'Пока ничего не выучено.',
    emptyAll: 'Слов нет.',
    emptyHidden: 'Ничего не скрыто. Сюда попадают слова, которые вы отметили как известные.',
    emptyFiltered: 'Ничего не найдено.',
    count: (shown) => `${shown} ${words(shown)}`,
    open: (word) => `Открыть: ${word}`,
    detail: {
      progress: 'Прогресс',
      scheduling: 'Расписание повторов',
      state: 'Состояние',
      repetitions: 'Повторений',
      interval: 'Интервал',
      nextReview: 'Следующий повтор',
      notScheduled: 'Не запланирован',
      dueNow: 'пора повторить',
      ease: 'Коэффициент лёгкости',
      noteHidden: 'Отмечено как известное: скрыто из Learn, Review и упражнений. Прогресс сохранён, поэтому после возвращения слово продолжит с того же места.',
      noteReference: (why) => `Только для справки: ${why}, поэтому слово не попадает ни в Learn, ни в Review.`,
      reasonPos: 'слова такого типа не заучивают',
      reasonNoTranslation: 'у слова пока нет перевода',
    },
  },

  interval: {
    minutes: (n) => `${n} мин`,
    days: (n) => `${n} д`,
    months: (n) => `${n} мес`,
    years: (n) => `${n} г`,
  },

  theme: {
    names: { system: 'Системная', light: 'Светлая', dark: 'Тёмная' },
  },

  settings: {
    title: 'Настройки',
    learning: 'Обучение',
    dailyGoal: 'Дневная цель',
    dailyGoalHint: 'Новых слов в день',
    decrease: 'Уменьшить дневную цель',
    increase: 'Увеличить дневную цель',
    sessionsNote: 'Цель от 16 слов делится на порции по 10: между ними вы будете возвращаться в Learn.',
    translation: 'Переводы',
    translationHint: 'Показывать русский, английский или оба. Один остаётся включённым.',
    russian: 'Русский',
    english: 'Английский',
    language: 'Язык',
    uiLanguage: 'Язык приложения',
    uiLanguageNames: { en: 'English', ru: 'Русский' },
    appearance: 'Оформление',
    theme: 'Тема',
    notifications: 'Уведомления',
    reminders: 'Напоминания — скоро',
    remindersHint: 'Они будут приходить через бота.',
    about: 'О приложении',
    version: 'Версия',
    bot: 'Открыть бота',
    aboutText: 'Приложение в разработке. Слова можно учить и повторять, прогресс сохраняется.',
    placementTest: 'Пройти входной тест',
    placementNone: 'Learn начнёт с самых частых слов.',
    placementAt: (rank) => `Learn будет брать слова в основном начиная с №${rank} по частотности, но не только.`,
    howItWorks: 'Как это работает',
    runIntro: 'Показать введение снова',
    debug: 'Debug',
  },

  onboarding: {
    stepOf: (n, m) => `Шаг ${n} из ${m}`,
    progress: 'Ход введения',
    back: 'Назад',
    continue: 'Дальше',
    done: 'Готово',
    language: { title: 'Язык приложения', text: 'Выберите язык, на котором будет приложение.' },
    about: { sentence: 'Испанский, на котором говорят в Уругвае и Аргентине, а не тот, что в учебнике.' },
    inside: {
      title: 'Что внутри',
      items: [
        { id: 'learn', name: 'Learn', text: 'новые слова, каждое сразу в живом предложении, а не списком.', tone: 'learn' },
        { id: 'review', name: 'Review', text: 'карточки для самопроверки: вы отмечаете, вспомнили или нет, а приложение решает, когда показать слово снова.', tone: 'learn' },
        { id: 'practice', name: 'Matching и Cloze', text: 'два других способа повторить: собрать пары слово — перевод или вставить пропущенное слово в предложение.', tone: 'practice' },
        { id: 'words', name: 'Words', text: 'весь словарь: поиск, фильтры, избранное и слова, которые вы добавили сами.', tone: 'learn' },
      ],
    },
    translation: {
      title: 'Переводы',
      text: 'Показывать русский, английский или оба перевода рядом с каждым словом.',
      names: { ru: 'Русский', en: 'Английский', both: 'Оба' },
      note: 'Это можно изменить в настройках.',
    },
    placement: {
      title: 'Входной тест',
      question: 'Какие из этих слов вы знаете?',
      hint: 'Отмечайте только те слова, значение которых вы знаете точно.',
      set: (n, m) => `Набор ${n} из ${m}`,
      progress: 'Ход теста',
      back: 'Назад',
      next: 'Дальше',
      finish: 'Завершить',
      skip: 'Пропустить',
      skipNote: 'Тест можно пройти позже в настройках.',
      unavailable: 'Новых слов осталось слишком мало для теста.',
    },
    goal: { title: 'Дневная цель', text: 'Новых слов в день' },
    pronunciation: {
      title: 'Произношение',
      facts: [
        [{ es: 'll' }, { text: ' и ' }, { es: 'y' }, { text: ' звучат примерно как «ш»: ' }, { es: 'calle' }, { text: ', ' }, { es: 'yo' }, { text: '.' }],
        [{ text: 'Говорят «' }, { es: 'vos tenés' }, { text: '» там, где в учебнике «' }, { es: 'tú tienes' }, { text: '».' }],
      ],
      link: 'Как это работает',
    },
  },

  howItWorks: {
    title: 'Как это работает',
    sections: [
      {
        id: 'learn',
        heading: 'Learn',
        text: 'Learn приносит новые слова небольшими порциями, в пределах дневной цели. На карточке слово, пример предложения и перевод. Когда порция закончена, её слова попадают в ваше расписание. Слово, которое вы уже знаете, можно отметить как известное: оно больше не появится ни в Learn, ни в Review, ни в упражнениях.',
      },
      {
        id: 'review',
        heading: 'Review',
        text: 'Review показывает слова, которые пора повторить. Переверните карточку и отметьте, насколько хорошо вы знали слово: «Снова», «Трудно», «Хорошо» или «Легко». От этого ответа зависит, когда слово вернётся.',
      },
      {
        id: 'matching',
        heading: 'Matching',
        text: 'В Matching нужно соединить испанские слова с их переводами. Берутся слова, которые вы уже выучили.',
      },
      {
        id: 'cloze',
        heading: 'Cloze',
        text: 'Cloze показывает предложение, в котором пропущено слово. Вы вводите пропущенное слово. Подсказка и ответ доступны в одно касание. Здесь тоже берутся уже выученные слова.',
      },
      {
        id: 'spaced',
        heading: 'Почему слово возвращается',
        text: 'Слова возвращаются по расписанию. Только что выученное слово нужно повторить на следующий день. Если вы его знали, следующий промежуток — несколько дней, потом около недели, потом недели и месяцы, и каждый длиннее предыдущего. Слово лучше всего удерживается в памяти, когда его снова видишь ровно в тот момент, когда оно начинает забываться, поэтому каждый удачный ответ отодвигает следующий повтор. Ответ «Снова» начинает слово заново, и оно скоро вернётся. Маленькое число на кнопке оценки — промежуток, который даёт этот ответ.',
      },
    ],
  },

  learn: {
    title: 'Learn',
    wordNofM: (n, m) => `Слово ${n} из ${m}`,
    swipeHint: 'Листайте или используйте стрелки',
    alreadyKnow: 'Я уже знаю это слово',
    markedKnown: (word) => `«${word}» отмечено как известное`,
    undo: 'Отменить',
    previous: 'Предыдущее',
    next: 'Следующее',
    finishBatch: 'Закончить порцию',
    learnNextBatch: 'Следующая порция',
    reviewDueWords: (n) => `Повторить слова (${n})`,
    newWordsToday: (n, limit) => `Новых слов сегодня: ${n} из ${limit}`,
    capReachedTitle: 'На сегодня новых слов достаточно',
    capReachedSubtitle: 'Хорошая работа. Завтра будут новые.',
    poolEmptyTitle: 'Новых слов пока нет.',
    poolEmptySubtitle: 'Learn показывает слова, которые вы ещё не учили.',
  },

  review: {
    title: 'Review',
    progress: (n, m) => `${n} / ${m}`,
    cardNofM: (n, m) => `Карточка ${n} из ${m}`,
    tapToReveal: 'Нажмите, чтобы открыть',
    howWell: 'Насколько хорошо вы знали слово?',
    again: 'Снова',
    hard: 'Трудно',
    good: 'Хорошо',
    easy: 'Легко',
    emptyTitle: 'Нет карточек для повторения',
    emptyMessage: 'Сначала закончите порцию в Learn.',
    goLearn: 'Learn',
    allCaughtUp: 'Всё повторено',
    allCaughtUpSubtitle: 'Сейчас нет карточек, которые пора повторить.',
    refresh: 'Обновить',
    sessionDone: 'Пока всё',
    sessionLeft: (n) => `Осталось повторить: ${n} ${words(n)}.`,
    continue: 'Продолжить',
  },

  practice: {
    matchingButton: 'Практика: Matching',
    clozeButton: 'Практика: Cloze',
    needWords: 'Нужно 5+ слов',
    matchingTitle: 'Matching',
    matchingHint: 'Выберите слово, затем его перевод.',
    matchingInsufficient: 'Сначала выучите и повторите несколько слов, потом возвращайтесь к Matching.',
    groupComplete: 'Группа пройдена',
    nextGroup: 'Следующая группа',
    clozeTitle: 'Cloze',
    clozeInsufficient: 'Сначала выучите и повторите несколько слов с примерами, потом возвращайтесь к Cloze.',
    answerLabel: 'Ваш ответ',
    hint: 'Подсказка',
    reveal: 'Показать ответ',
    check: 'Проверить',
    continue: 'Дальше',
    correct: 'Верно!',
    accentNudge: (form) => `Проверьте знак ударения: ${form}`,
    wrong: (form) => `Не совсем — нужное слово: ${form}`,
    gaveUp: (form) => `Нужное слово: ${form}`,
    sessionComplete: 'Сессия завершена',
    score: (n, m) => `Верно: ${n} из ${m}`,
    newSession: 'Новая сессия',
    outcome: { correct: 'Верно', wrong: 'Неверно', gaveUp: 'Не вспомнили' },
    backHome: 'На главный экран',
    progressLabel: 'Ход по вопросам',
  },

  card,

  wordContent,

  rio: {
    pill: 'риоплатское',
    rioplatense: 'Риоплатская форма',
    also: 'также',
    standard: 'стандарт',
    stdUsageHint: { equally_used: 'тоже в ходу', less_common: null, not_used: 'здесь почти не говорят' },
    note: 'Заметка',
    standardMeaning: 'Обычное значение',
    register: { informal: 'разговорное', vulgar: 'вульгарное', offensive: 'оскорбительное', pejorative: 'пренебрежительное' },
    tag: { uy: 'UY', ar: 'AR' },
    tagTitle: { uy: 'Употребляется в Уругвае', ar: 'Употребляется в Аргентине' },
  },

  pos: {
    v: 'Глагол',
    n: 'Существительное',
    adj: 'Прилагательное',
    adv: 'Наречие',
    custom: 'Другое',
    prop: 'Имя собственное',
    pron: 'Местоимение',
    num: 'Числительное',
    prep: 'Предлог',
    determiner: 'Определитель',
    conj: 'Союз',
    interj: 'Междометие',
    letter: 'Буква',
    contraction: 'Слитная форма',
    art: 'Артикль',
  },

  debug,
}
